zairza-cetb/hacktoberfest-2018

search/binary_search/C++/binary_search.cpp

The Pull Request resolves Issue #4 
Description:
C++ code for binary search

C++ code for binary serach ( Issue #4 )

---

search/binary_search/JavaScript/binary_search.js

The Pull Request resolves Issue #4 
Description:
JavaScript implementation of binary search.

JavaScript binary search - Issue #4

---

data_structures/linked_lists/go/list.go
data_structures/linked_lists/go/list_test.go

The Pull Request resolves Issue #17
Description:
Implement a generic linked list in Go. It also includes tests with 100% code coverage.

Create linked list in Go

---

data_structures/linked_lists/LinkedList.c

The Pull Request resolves Issue #17 
Description:
Linked list data structure is implemented in C. It has functions mainly for following tasks:
- To insert an element in the list.
- To delete an existing element from the list.
- To reverse the linked list.
- To print the elements of the list.

Linked List implementation in C

---

sort/bubble_sort/Java/BubbleSort.java
sort/insertion_sort/Java/InsertionSort.java

The Pull Request resolves Issue #1 and #3
Description:
add java code for bubble sort.
add java code for insertion sort.

add java code for bubble sort and insertion sort

---

sort/insertion_sort/cpp/insertionSort.cpp
sort/quick_sort/cpp/quicksort.cpp

added quicksort cpp

---

data_structures/linked_lists/linkedlist.java

Implemented Linked List in java
The Pull Request resolves Issue #<IssueNumber>
Description:
A brief description about the addition or edits made.
Notes: Delete all the text including this!
* The pull request made should be in the prescribed format.
* The  `#<IssueNumber>` should be replaced with the specific Issue being referenced!
* Reviewers should be added in order to review the pull request made. Adding more number of reviewers helps in getting the PR merged faster.

LinkedList

---

data_structures/linked_lists/js/linkedList.js

The Pull Request resolves Issue #<IssueNumber>
Description:
A brief description about the addition or edits made.
Notes: Delete all the text including this!
* The pull request made should be in the prescribed format.
* The  `#<IssueNumber>` should be replaced with the specific Issue being referenced!
* Reviewers should be added in order to review the pull request made. Adding more number of reviewers helps in getting the PR merged faster.

Implemented linked list in JavaScript

---

data_structures/linked_lists/java/linkedlist.java
data_structures/linked_lists/linkedlist.py
sort/insertion_sort/python/insertion-sort.py

The Pull Request resolves Issue #3 
Description:
Insertion sort using python.

Python insertion sort

---

data_structures/linked_lists/cpp/reverse linked list

The Pull Request resolves Issue #17 
Description:
* code to reverse a linked list in c++
* the reverse function is implemented using recursion

added code to reverse linked list

---

sort/merge_sort/go/sort.go
sort/merge_sort/go/sort_test.go

The Pull Request resolves Issue #7 
Description:
Implement merge sort using golang

Add golang merge sort example

---

data_structures/stacks/stack.c
sort/selection_sort/selection_sort.java

The Pull Request resolves Issue #<68>
Implemented sort algorithms using c

implementation of stack using c

---

dynamic_programing/longest_common_subsequence/LongestSubSeq.cpp

The Pull Request resolves Issue #16 
Description:
Added code for length of longest increasing subsequence in c++.

Added code for length of longest increasing subsequence

---

sort/selection_sort/python/selection_python

The Pull Request resolves Issue #60 
Description:
Added code for implementing selection sort using Python
Notes: Delete all the text including this!
* The pull request made should be in the prescribed format.
* The  `#<IssueNumber>` should be replaced with the specific Issue being referenced!
* Reviewers should be added in order to review the pull request made. Adding more number of reviewers helps in getting the PR merged faster.

Implentation of selection sort using Python

---

sort/heap_sort/java/HeapSort.java

The Pull Request resolves Issue #<58>
Description:
Heap Sort implementation in JAVA

heap sort implementation in java

---

search/ternary_search/c++/ternary_search.cpp

The Pull Request resolves Issue #<54>
Description:
Implemented Ternary Search using c++.

Added implementtion of ternary search in c++

---

search/jump_search/Java/JumpSearch.java

The Pull Request resolves Issue  #51
Description:
Jump Search implementation in Java

Jump Search in Java

---

sort/heap_sort/CPP/heapsort_cpp

The Pull Request resolves Issue #58

Implemented Heap Sort using CPP.

---

dynamic_programing/longest_common_subsequence/python/LCS_python.py

The Pull Request resolves Issue #<16>
The files is in a separate sub-directory, as was requested.

Implemented LCS in python #16

---

sort/insertion_sort/go/insertion_sort.go

The Pull Request resolves Issue #3 
Description:
Implemented insertion sort in go.

Implement insertion sort in go #3

---

data_structures/linked_lists/circularLL.c

The Pull Request resolves Issue #128
Implemented Circular linked list in C

Implemented Circular Linked List in C

---

graph_algorithms/breadth_first_search/bfs.cpp
graph_algorithms/depth_first_search/dfs.cpp
graph_algorithms/dijkstras_algorithm/dijkstra.cpp

Description:
Added codes for breadth-first-search, depth-first-search, and Dijkstra's algorithm in the folder Graph Algorithm.

added bfs, dfs, dijkstra code in c++

---

data_structures/BST/Makefile
data_structures/BST/README.md
data_structures/BST/bst1.h
data_structures/BST/main.cpp

The Pull Request resolves Issue #120 
Description:
Implementation of BST

added BST implementation

---

sort/insertion_sort/go/insertion_sort.go
sort/radix_sort/go/radix_sort.go

The Pull Request resolves Issue #11
Description:
Add go code for radix sort.

Implement radix sort in go

---

graph_algorithms/depth_first_search/python/dfs.py

The Pull Request references Issue #42

Add depth_first_search in python 2

---

search/interpolation_search/go/search.go
search/interpolation_search/go/search_test.go

The Pull Request resolves Issue #49 
Description:
Implement interpolation search using golang

Add golang interpolation search example

---

sort/heap_sort/python/heap_sort.py

The Pull Request resolves Issue #58 
Description:
This heap sort implementation is done in Python using recursive heapifying. Driver code is included.

Added Heap sort algorithm in Python

---

search/binary_search/Csharp/binary_search.cs

The Pull Request resolves Issue #4 
Description:
Implement binary search in C#.

Implement binary search in C#

---

sort/insertion_sort/Bash/insertion_sort

The Pull Request resolves Issue #55
Description:
Adding insertion sort implementation in bash

Adding insertion sort implementation in bash

---

search/binary_search/python/binary.py

The Pull Request resolves Issue #<4>
Description:
implementation of binary search using python

binary search using python

---

sort/merge_sort/python/mergesort.py

The Pull Request resolves Issue #7 
Implemented merge sort for lists in Python

merge sort in python

---

sort/selection_sort/selectionsort.go
sort/selection_sort/selectionsort_test.go

The Pull Request resolves Issue #60 
Description:
Implement selection sort in golang. The function receives a comparison
function too.
Notes: 
- Execute by running `go run selectionsort.go` in a terminal window.
- Execute tests by running `go test *.go`.
**_The commands above must be executed within the solution folder._**

Implement selection sort in golang

---

search/interpolation_search/Java/InterpolationSearch.java

The Pull Request resolves Issue #49
Description:
Java implementation of interpolation search

Java implementation of interpolation search

---

data_structures/linked_lists/cpp/SinglyLinkedList/singly_linked_list.cpp
data_structures/linked_lists/cpp/SinglyLinkedList/singly_linked_list.h

The Pull Request resolves Issue #17 
Description:
This adds implementation of basic
singly linked list operations in c++

Add Singly LinkedList in C++

---

data_structures/binary_search_tree/Cpp/BinarySearchTree.cpp
data_structures/binary_search_tree/Cpp/BinarySearchTree.h

The Pull Request resolves Issue #119 
Description:
Implementation of Binary search tree operations in C++

Add Binary search tree implementation in C++

---

sort/heap_sort/golang/heapsort.go
sort/heap_sort/golang/heapsort_test.go

The Pull Request resolves Issue #58 
Description:
Implement heap sort in golang. Tests are included.
Notes: 
- Execute by running `go run heapsort.go` in a terminal window.
- Execute tests by running `go test *.go`.
**_The commands above must be executed within the solution folder._**

Implement heap sort in golang

---

search/binary_search/go/binary_search.go
search/binary_search/go/binary_search_test.go

The Pull Request resolves Issue #4
Description:
Implements binary search in go

implement binary search in go

---

graph_algorithms/dijkstras_algorithm/python/dijkstras_algorithm.py

The Pull Request resolves Issue #72

Add dijkstras_algorithm in Python2

---

search/linear_search/javascript/linearsearch.js

The Pull Request resolves Issue #52 
Description:
Added linear search implementation with javascript

linear search js

---

sort/insertion_sort/rust/main.rs

implement insertion sort in rust

---

graph_algorithms/dijkstras_algorithm/golang/dijkstra.go
graph_algorithms/dijkstras_algorithm/golang/dijkstra_test.go

The Pull Request resolves Issue #72 
Description:
Implement Dijkstra's algorithm for shortest distance in Golang. Tests are included.
Notes:
- Execute by running `go run dijkstra.go` in a terminal window.
- Execute tests by running `go test *.go`.
**_The commands above must be executed within the solution folder._**

Implement Dijkstra's algorithm in Golang

---

data_structures/Trie/trie.py

Add trie implementation in python

---

data_structures/Hash Map/HashMap.cpp
data_structures/Hash Map/HashMap.h
data_structures/Hash Map/Read me
data_structures/Hash Map/Source.cpp

The Pull Request resolves Issue #<IssueNumber>
Description:
A brief description about the addition or edits made.
Notes: Delete all the text including this!
* The pull request made should be in the prescribed format.
* The  `#<IssueNumber>` should be replaced with the specific Issue being referenced!
* Reviewers should be added in order to review the pull request made. Adding more number of reviewers helps in getting the PR merged faster.

Create a Hash Map DS example 

---

sort/Bogo_sort/permutation_bogosort.cpp
sort/Bogo_sort/readme.txt

The Pull Request resolves Issue #183 
Description:
A Permutation sorting algorithm

added permutation or Bogo_sort

---

sort/selection_sort/shell/selectionsort.sh

The Pull Request resolves Issue #60 
Description:
Created a .sh file containing the implementation of the SelectionSort Algorthim on path ./sort/selection_sort/shell/selectionsort.sh}.

Add SelectionSort in Shell Script Language
